// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.26.1
// source: vector.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X []int64 `protobuf:"varint,2,rep,packed,name=x,proto3" json:"x,omitempty"`
	Y []int64 `protobuf:"varint,3,rep,packed,name=y,proto3" json:"y,omitempty"`
	R float32 `protobuf:"fixed32,4,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *VectorInput) Reset() {
	*x = VectorInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorInput) ProtoMessage() {}

func (x *VectorInput) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorInput.ProtoReflect.Descriptor instead.
func (*VectorInput) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{0}
}

func (x *VectorInput) GetX() []int64 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *VectorInput) GetY() []int64 {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *VectorInput) GetR() float32 {
	if x != nil {
		return x.R
	}
	return 0
}

type VectorProductResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *VectorProductResult) Reset() {
	*x = VectorProductResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorProductResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorProductResult) ProtoMessage() {}

func (x *VectorProductResult) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorProductResult.ProtoReflect.Descriptor instead.
func (*VectorProductResult) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{1}
}

func (x *VectorProductResult) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type VectorResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A float32 `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B float32 `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *VectorResult) Reset() {
	*x = VectorResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorResult) ProtoMessage() {}

func (x *VectorResult) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorResult.ProtoReflect.Descriptor instead.
func (*VectorResult) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{2}
}

func (x *VectorResult) GetA() float32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *VectorResult) GetB() float32 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_vector_proto protoreflect.FileDescriptor

var file_vector_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x37, 0x0a, 0x0b, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x01,
	0x79, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x72, 0x22,
	0x2d, 0x0a, 0x13, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2a,
	0x0a, 0x0c, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0c,
	0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01,
	0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x62, 0x32, 0xc8, 0x01, 0x0a, 0x06, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x40, 0x0a, 0x0c, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x13, 0x2e, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3a, 0x0a, 0x0d, 0x41, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x14, 0x2e,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x40, 0x0a, 0x13, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x13, 0x2e, 0x76, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x14, 0x2e, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vector_proto_rawDescOnce sync.Once
	file_vector_proto_rawDescData = file_vector_proto_rawDesc
)

func file_vector_proto_rawDescGZIP() []byte {
	file_vector_proto_rawDescOnce.Do(func() {
		file_vector_proto_rawDescData = protoimpl.X.CompressGZIP(file_vector_proto_rawDescData)
	})
	return file_vector_proto_rawDescData
}

var file_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vector_proto_goTypes = []interface{}{
	(*VectorInput)(nil),         // 0: vector.VectorInput
	(*VectorProductResult)(nil), // 1: vector.VectorProductResult
	(*VectorResult)(nil),        // 2: vector.VectorResult
}
var file_vector_proto_depIdxs = []int32{
	0, // 0: vector.Vector.InnerProduct:input_type -> vector.VectorInput
	0, // 1: vector.Vector.AverageValues:input_type -> vector.VectorInput
	0, // 2: vector.Vector.ScalarVectorProduct:input_type -> vector.VectorInput
	1, // 3: vector.Vector.InnerProduct:output_type -> vector.VectorProductResult
	2, // 4: vector.Vector.AverageValues:output_type -> vector.VectorResult
	2, // 5: vector.Vector.ScalarVectorProduct:output_type -> vector.VectorResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vector_proto_init() }
func file_vector_proto_init() {
	if File_vector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorProductResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vector_proto_goTypes,
		DependencyIndexes: file_vector_proto_depIdxs,
		MessageInfos:      file_vector_proto_msgTypes,
	}.Build()
	File_vector_proto = out.File
	file_vector_proto_rawDesc = nil
	file_vector_proto_goTypes = nil
	file_vector_proto_depIdxs = nil
}
